---
title: "iteration_and_listcols"
author: "Juliet Rowe"
date: "2023-10-31"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

set.seed(12345)
```


### Lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(
  num = vec_numeric,
  char = vec_char
)
```

Different stuff with different lengths

```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow=5, ncol=2),
    summary = summary(rnorm(100))
  )
```


Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```


### Loops

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

```


```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```


```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)



```


```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
}
```



